spring:
  port: ${PORT:8081}    # 8081 port는 dev환경
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MariaDBDialect
  batch:
    jdbc:
      initialize-schema: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: method

---
spring:
  application:
    name: batch-local, batch-dev
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL}
